### PR TITLE
add code so tests run in newer versions of django

### PR DESCRIPTION
**Pull request by JBKahn**
DiscoverRunner was added in 1.6 and tests will not run in newer versions of Django due to changes in the application loading. A fix that will make the test runner run/pass.

### CODE REVIEW

**Comment by dlanger** [comment]
@JBKahn I'll merge this in when I do that other one, and then do a version-bump and proper release.

**Comment by JBKahn** [comment]
support for 2.6 dropped. Limit to Django 1.6 or drop tests for 2.6?

**Comment by JBKahn** [comment]
@dlanger ^

**Comment by dlanger** [comment]
Drop 2.6

**Comment by dlanger** [comment]
Can you also update the classifiers in `setup.py` to show that it's 1.6+?

**Comment by JBKahn** [comment]
It didn't list versions, but I can add that info.

**Pull request merged**
