### PR TITLE
on RequestException in participate, return the forced bucket if its part...

### PR DESCRIPTION
**Pull request by JBKahn**
... of the experiment

### CODE REVIEW

**Comment by dlanger** [comment]
Also, add your name to the `AUTHORS` file.

**Comment by JBKahn** [comment]
Will do both

**Comment by JBKahn** [comment]
This was the change that broke the test, I'm guessing the test just wasn't updated to not include the kpi.
https://github.com/waveaccounting/django-sixpack/blob/participate_RequestException_handling/djsixpack/djsixpack.py#L94

**Comment by dlanger** [comment]
Sorry, can you also bump the version in the appropriate places and start a `CHANGELOG` file? We'll make a new release out of this.

**Comment by JBKahn** [comment]
sure

**Comment by dlanger** [comment]
:+1: - I'll merge and push a new version after lunch?

**Comment by dlanger** [comment]
Something's up with the RST in the README - aside from that, LGTM.

**Comment by JBKahn** [comment]
I'll fix it now

**Pull request merged**
